name-template: 'scribl $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
#prerelease: true
include-pre-releases: true
#prerelease-identifier: 'rc'
#version-template: '$COMPLETE'
commitish: 'main'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'installation'
  - title: 'Internal'
    labels:
      - 'github_actions'
      - 'dependencies'
  - title: 'Documentation'
    labels:
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
category-template: '### $TITLE'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog:** https://github.com/amberbiology/scribl/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
