name-template: 'scribl $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
prerelease: false
include-pre-releases: false
#prerelease-identifier: 'rc'
version-template: '$COMPLETE'
commitish: 'main'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'installation'
  - title: 'Internal'
    labels:
      - 'github_actions'
      - 'dependencies'
  - title: 'Documentation'
    labels:
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
category-template: '### $TITLE'
change-template: '- $TITLE by @$AUTHOR ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Install via PyPI
  ```
  pip install -U scribl
  ```
  <!-- START cut-and-paste to CHANGELOG.md -->

  ## [$RESOLVED_VERSION] - YYYY-MM-DD

  $CHANGES

  [$RESOLVED_VERSION]: https://github.com/$OWNER/$REPOSITORY/releases/tag/v$RESOLVED_VERSION

  <!-- END cut-and-paste to NEWS.md -->

  A full history of changes is available in [`CHANGELOG.md`](https://github.com/$OWNER/$REPOSITORY/blob/main/CHANGELOG.md).

  **Full Changelog:** https://github.com/amberbiology/scribl/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
